# Generated by Django 2.1.7 on 2019-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_auto_20190427_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
