# Generated by Django 2.1.7 on 2019-05-02 18:30

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_article_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1line', 'one line paragraph'), ('split', 'split paragraph')], default='1line', max_length=20)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='blog_site.Article'),
        ),
    ]
