# Generated by Django 2.1.7 on 2019-05-03 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0005_auto_20190502_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_site.Article'),
        ),
    ]
