# Generated by Django 2.1.7 on 2019-05-02 00:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190501_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='imgs/limbi.png', upload_to=accounts.models.save_profile_pic),
        ),
    ]
