# Generated by Django 2.2.5 on 2019-10-27 09:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190502_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/static/imgs/avatar/default.png', upload_to=accounts.models.save_profile_pic),
        ),
    ]
