# Generated by Django 2.2.5 on 2019-10-27 09:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191027_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default/default.png', upload_to=accounts.models.save_profile_pic),
        ),
    ]
