# Generated by Django 2.2.5 on 2019-12-26 21:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191027_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/default.png', upload_to=accounts.models.save_profile_pic),
        ),
    ]
